#!/bin/bash
# 
# Copyright (C) Niklaus F.Schen.
# 
if test -d melon; then
	echo "Thank you for choosing Portal."
else
	echo "Please install before starting up."
	exit 1
fi
function printHelp()
{
	echo "$0 type"
	echo "Type:"
	echo -e "\tproxy_server"
	echo -e "\tproxy_client"
	echo -e "\ttunnel_server"
	echo -e "\ttunnel_client"
	echo -e "\tbroadcaster"
}
if [ ! -n "$1" ]; then
	printHelp
	exit 1
fi
confFile=confs/melon.conf.$1
if [ ! -f "$confFile" ]; then  
	echo "Invalid type."
	printHelp
fi 
cp confs/melon.conf.$1 melon/conf/melon.conf && ./portal
